### ISSUE TITLE
Horrible documentation!

### ISSUE THREAD

**Issue by Joebeazelman** [TheCase/IPMIView.app#9]
Your installation instructions just sucks! Just two measly minutes of your time would eliminate a good deal of the issues created here. You instruct the user to install the latest release from supermicro's FTP site and then instruct them to execute a bunch of shell scripts. What folder are they supposed to be in?  Where do they download IPMIView to? I am assuming the shell scripts create the App bundle and the user is supposed to unarchive the downloaded IPMIView inside it.

If you have a problem writing in the English language, you might want to just have your script do the right thing. How can you even reveal your face on your profile after putting out such mediocrity?

**Comment by TheCase** [comment]
[https://www.dictionary.com/browse/you-can-catch-more-flies-with-honey-than-with-vinegar](https://www.dictionary.com/browse/you-can-catch-more-flies-with-honey-than-with-vinegar
)

1. Open Source Software: I decided to share this code that I developed on my own free time.  I don't get paid to work on it.  I shared it to be nice to others that might find it useful.  I would hope you would treat me nicely for sharing it with you.  If you have an issue with open source software on GitHub, it is possible to create an issue without downright insulting the author.

2. Download directory: as clearly seen in the shell script, it is the Downloads folder in your home directory` ~/Downloads`.  I have made this crystal clear in the updated documentation. 

3. Function: it is indeed a shell script that performs the functions necessary to turn the SuperMicro's Linux package into an Application Bundle that will run on your Mac.  The script takes care of the unarchiving.  That's why I didn't mention it in the README.  If you follow the instructions as written, it works.  If you still have issues, please file a proper issue report with details about what you expect the software to do and clearly document where it is failing.  Cutting and pasting the actual error output into the issue is extremely helpful. 

4. Quality: If you think can do a better job, please fork this repository and go for it.

5. Have a nice day!

**Comment by TheCase** [comment]
updated documentation a41bc50ad5489c041b48c2a558147817368e0e1f

**Comment by Joebeazelman** [comment]
I’m terribly sorry about my mean spirited comments. Not to justify any of it, I want you to at least understand where I think it came from. It had nothing to do with your documentation. I’ve been a programming since childhood, culminating in over 30 years. I’ve been involved with several commercial applications and mentored many young engineers over the years. I have a CS degree and know numerous platforms and languages. 

Over the past 8 months, I received a rude awakening. Despite my experience, it has been over 8 months of grueling job hunting where I’ve been subjected to the most inhumane treatment known to man: white boarding. It is just one step lower on the torture scale than its sibling waterboarding.  Imagine having someone young enough to be your child laugh at you because you have difficulty recalling some arcane SQL syntax?  After enough of these interviews, you really begin to question your own competence and begin to reconsider other career options. At the same time, however, you wonder how bad can you be when there’s so much bad software out there. Your code, in particular, is brilliant and underserving of my bile.

Again, I’m deeply sorry for my angry comments. I also commend you for dealing with it with such dignity and elegance. You’re clearly the better man here.

**Comment by TheCase** [comment]
Thank you for the apology. Given the polarization between your two comments, I suggest to stay away from the keyboard after drinking and/or seek some professional help.

**Comment by weitzhandler** [comment]
> Given the polarization between your two comments

He deleted the apology...

**Comment by TheCase** [comment]
Oh geez. Whatever.
